### ISSUE TITLE
Error when trying to patch RSTB

### ISSUE THREAD

**Issue by vewsga** [ShrineFox/RSTBPatcher#4]
After I set every path in the GUI and try to patch the RSTB an error occurs (unknown frame descriptor). I'm using Windows 10 and have Net Core 7.0.4 installed.

**Comment by ShrineFox** [comment]
It seems like this only happens when a file ending with the extension .zs isn't actually ZSTD compressed. This could end up being the case when someone making a mod with [Switch Toolbox](https://github.com/KillzXGaming/Switch-Toolbox) says no (either accidentally or on purpose) when prompted to compress a file while saving.  
For now, the best workaround is to re-save any .zs files (usually models) in Toolbox that seem to have a suspiciously large filesize, but perhaps I could add a prompt or warning when this happens since there might be good reasons to intentionally leave a file uncompressed (i.e. testing). Thanks for bringing this to my attention!

**Comment by vewsga** [comment]
Thanks for the answer! Compressed all Model files again and it worked. 

For everyone who has the problem that Toolbox doesn't ask If you  want to compress the file:
 When this happens, you need to compress them manually by going to tools -> compression -> ZSTD -> compress and selecting the file(s) and the output file / folder.
